Implemented article and cover letter upload

diff --git a/init b/init
--- a/init
+++ b/init
@@ -78,5 +78,11 @@ if [ $? -ne 0 ]; then
     err "Error while setting permissions."
 fi
 
+log "Linking public directory"
+docker exec laravel php artisan storage:link
+if [ $? -ne 0 ]; then
+    err "Error while linking public directory."
+fi
+
 # log "Copying the pre commit hook"
 # cp pre-commit .git/hooks/pre-commit
